# Generated by Django 3.1.6 on 2021-04-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pos', models.DateTimeField(auto_now_add=True)),
                ('judul', models.CharField(max_length=100)),
                ('konten', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ['-waktu_pos'],
            },
        ),
        migrations.CreateModel(
            name='Pelatih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nama_panggilan', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('bagi_hasil', models.FloatField(default=0.6)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-nama_panggilan'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('jumlah_pertemuan', models.IntegerField()),
            ],
            options={
                'ordering': ['nama_produk'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nama_panggilan', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('usia', models.IntegerField()),
            ],
            options={
                'ordering': ['-nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskon', models.FloatField(blank=True, null=True)),
                ('tgl_transaksi', models.DateField()),
                ('tgl_habis', models.DateField()),
                ('arsip', models.BooleanField(default=False)),
                ('p1', models.DateField(blank=True, null=True, verbose_name='Pertemuan 1')),
                ('p2', models.DateField(blank=True, null=True, verbose_name='Pertemuan 2')),
                ('p3', models.DateField(blank=True, null=True, verbose_name='Pertemuan 3')),
                ('p4', models.DateField(blank=True, null=True, verbose_name='Pertemuan 4')),
                ('p5', models.DateField(blank=True, null=True, verbose_name='Pertemuan 5')),
                ('p6', models.DateField(blank=True, null=True, verbose_name='Pertemuan 6')),
                ('p7', models.DateField(blank=True, null=True, verbose_name='Pertemuan 7')),
                ('p8', models.DateField(blank=True, null=True, verbose_name='Pertemuan 8')),
                ('p1_c', models.BooleanField(default=False)),
                ('p2_c', models.BooleanField(default=False)),
                ('p3_c', models.BooleanField(default=False)),
                ('p4_c', models.BooleanField(default=False)),
                ('p5_c', models.BooleanField(default=False)),
                ('p6_c', models.BooleanField(default=False)),
                ('p7_c', models.BooleanField(default=False)),
                ('p8_c', models.BooleanField(default=False)),
                ('pelatih', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pelatih')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produk')),
                ('siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.siswa')),
            ],
            options={
                'ordering': ['siswa'],
            },
        ),
    ]
